version: "3.9"
services:
  db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    networks:
      - db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  db:
volumes:
  db-data:
