app = "scoretune-api"
primary_region = "cdg"

[env]
    SPRING_PROFILES_ACTIVE = "prod"

[[services]]
    internal_port = 8080
    protocol = "tcp"

[[services.ports]]
    handlers = ["http"]
    port = 80

[[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    restart_limit = 0